### ISSUE TITLE
png logo is inconsistent with SVG logo

### ISSUE THREAD

**Issue by WolfgangFahl** [Open-CSP/open-csp#2]
https://github.com/Open-CSP/open-csp/tree/main/logo

![grafik](https://user-images.githubusercontent.com/1336221/198585355-779bfe7d-b675-429a-8d99-c46976bf3231.png)

**Comment by Designburo** [comment]
@wgevaert This is a good point. Can you take care of this ? See : https://github.com/Open-CSP/open-csp/tree/main/logo

**Comment by wgevaert** [comment]
Thank you for making this issue!
I have removed the other logo from the repository, it seems like it is not used.

Please let me know if you come across any other issues!
