### ISSUE TITLE
SQL error during installation. (on WSSpaces extension)

### ISSUE THREAD

**Issue by LarsS88** [Open-CSP/open-csp#4]
My SMW database uses the table prefix "mw_" which isn't added to a reference in the table definitions.
As a result when executing install_open_csp.sh and this calls update.php and then doMaintenance.php to update the database with tables for new extensions it first adds the wss_namespaces table correctly and then crashes on wss_namespace_admins with the error that it references a non-existing table.

The contents of extensions/WSSpaces/sql/mysql/wss_namespace_admins_table.sql was this:
`CREATE TABLE /*_*/wss_namespace_admins (
      namespace_id INT NOT NULL,
      admin_user_id INT NOT NULL,
      PRIMARY KEY ( namespace_id, admin_user_id ),
      FOREIGN KEY ( namespace_id )
          REFERENCES wss_namespaces( namespace_id )
          ON DELETE CASCADE
) /*$wgDBTableOptions*/;
`
So I had to manually edit it and fix it to this:
`CREATE TABLE /*_*/wss_namespace_admins (
      namespace_id INT NOT NULL,
      admin_user_id INT NOT NULL,
      PRIMARY KEY ( namespace_id, admin_user_id ),
      FOREIGN KEY ( namespace_id )
          REFERENCES mw_wss_namespaces( namespace_id )
          ON DELETE CASCADE
) /*$wgDBTableOptions*/;
`
After that, running install_open_csp.sh again, it was able to finish the installation.

**Comment by wgevaert** [comment]
Thank you for making this issue!

As you mentioned, this is a problem in the WSSpaces extension not correctly handling table prefixes (`$wgDBprefix`).
For future reference, the change is here:
```sql
[...] REFERENCES wss_namespaces( namespace_id ) ON DELETE CASCADE );
changed to 
[...] REFERENCES mw_wss_namespaces( namespace_id ) ON DELETE CASCADE );
```
I'll make an issue at the extension.

**Comment by LarsS88** [comment]
> ```sql
> changed to 
> [...] REFERENCES mw_wss_namespaces( namespace_id ) ON DELETE CASCADE );
> ```

No, no; the "mw_" is particular to my deployment.
The solution as it should be in the extension as distributed would be:
[...] REFERENCES /*_*/wss_namespaces( namespace_id ) ON DELETE CASCADE );

**Comment by wgevaert** [comment]
See https://github.com/Open-CSP/WSSpaces/pull/2

**Comment by wgevaert** [comment]
Should be fixed
